# display the count for git
[git_status]
	conflicted = "=${count}"
	ahead = "⇡${count}"
	behind = "⇣${count}"
	diverged = "⇕ ⇡${ahead_count}⇣${behind_count}"
	untracked = "?"
	stashed = "$${count}"
	modified = "!${count}"
	staged = "+${count}"
	renamed = "»${count}"
	deleted = "✘${count}"
	style = "bold blue"

[git_metrics]
	disabled = false

[git_commit]
	# commit length is short to minimise typing
	commit_hash_length = 5

